name: Basic Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Information
        run: |
          echo "Current Directory:"
          pwd
          echo "Repository Files:"
          ls

      - name: Display Date
        run: date

      - name: Display Git Version
        run: git --version